### ISSUE TITLE
CLI throws faulty error when outdir is passed to AppProps

### ISSUE THREAD

**Issue by pmkuny** [cdk8s-team/cdk8s-cli#210] opened 2022-02-24 23:29 UTC
### Description of the bug:

Configuration of the output directory `outdir` for manifests file in the App construct results in an error message with the default output directory (`dist`)

 I am using the following:
* Python 3.7.10
* cdk8s-cli 1.0.107
* cdk8s==1.5.8
* cdk8s-plus-22==1.0.0b109

### Reproduction Steps:

```
from constructs import Construct
from cdk8s import App, Chart
app = App(
    outdir="manifests"
)
```

### Error Log:

After running `cdk8s synth`:
```
ERROR: synthesis failed, app expected to create "dist"
```

### Environment:

  - **Framework Version**: 1.5.8
  - **OS**: AL2

```
attrs==21.4.0
cattrs==1.10.0
cdk8s==1.5.8
cdk8s-plus-22==1.0.0b109
constructs==3.3.209
jsii==1.52.1
publication==0.0.3
python-dateutil==2.8.2
six==1.16.0
typing_extensions==4.0.1
```

### Other:

---

This is :bug: Bug Report

**Comment by Chriscbr** [comment] 2022-02-25 01:26
@pmkuny I've gone ahead and transferred the issue straight over. Thanks!

**Comment by martimors** [comment] 2022-09-08 08:57
Faced this peculiar error message

```
ERROR: synthesis failed, app expected to create "dist"
```

although everything seems fine. The problem is that the exit code is 1, so this causes CI pipelines to fail. Using the default `dist/` directory for now. Just thought I'd chime in that this bug is still there in `2.0.105`.

**Comment by iliapolo** [comment] 2022-09-28 15:48
Yeah this is a silly one. Basically when the `outdir` is configured on the `App` instance, the CLI currently doesn't know about it, so it still thinks `dist` was used, and validates against that. 

We are looking into it, but for anyone interested in using a custom output directory, you can configure it using the `output` property in `cdk8s.yaml`, instead of the `App` instance. That should work fine.

**Closed** 2022-10-04 08:07 UTC
Labels: bug, effort/medium, priority/p1

**Comment by shinebayar-g** [comment] 2023-01-26 04:19
So `outdir` property doesn't work or is this fixed? I've this code and it didn't work.

```ts
const app = new App({
    outdir: 'manifests',
});

// error
Synthesizing application
ERROR: synthesis failed, app expected to create "dist"
```

However as suggested, setting `output: manifests` in `cdk8s.yaml` worked, thanks.
