### ISSUE TITLE
Importing Some CRDs causes 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by jhwbarlow** [cdk8s-team/cdk8s-cli#793] opened 2023-02-01 00:50 UTC
Hello 👋

```shell
node --version && cdk8s --version
v19.3.0
2.1.122
```

When importing some CRDs, specifically the Prometheus Operator CRDs that I currently have in my cluster (see gist [here](https://gist.github.com/jhwbarlow/8023d014dc59c63836293580e2dc2575)) `cdk8s import` causes the following exception:

```
Importing resources, this may take a few moments...
monitoring.coreos.com
  monitoring.coreos.com/alertmanager
  monitoring.coreos.com/alertmanagerconfig
  monitoring.coreos.com/podmonitor
  monitoring.coreos.com/probe
  monitoring.coreos.com/prometheus
  monitoring.coreos.com/prometheusrule
  monitoring.coreos.com/servicemonitor
  monitoring.coreos.com/thanosruler
NOTE: Temp directory retained due to an error: /var/folders/b9/jjbdk7l54_s3rt8404hc4hd40000gp/T/temp-TbuD5J
Error: jsii compilation failed with non-zero exit code: 255
  | Error: RangeError: Maximum call stack size exceeded
  |     at getPipelinePhase (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95407:34)
  |     at pipelineEmit (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95398:33)
  |     at emitExpression (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95384:20)
  |     at emitPropertyAccessExpression (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:96389:38)
  |     at pipelineEmitWithHint (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95780:32)
  |     at pipelineEmitWithSourceMap (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:99003:21)
  |     at pipelineEmitWithComments (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:98747:17)
  |     at maybePipelineEmitExpression (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:96599:21)
  |     at emitBinaryExpression (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:96554:25)
  |     at pipelineEmitWithHint (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95810:32)
  +----------------------------------------------------------------------------------
  | Command: /Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/b9/jjbdk7l54_s3rt8404hc4hd40000gp/T/temp-TbuD5J
  +----------------------------------------------------------------------------------
    at newError (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:62:20)
    at ChildProcess.<anonymous> (/Users/jamesbarlow/homebrew/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:79:29)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

This appears to be caused by the `thanosrulers.monitoring.coreos.com` CRD, as removing this from the `List` allows a successful import. However, what is strange is that importing the ThanosRuler CRD on its own also completes successfully. So it is something about that particular CRD in combination with the others that it does not like. Or it may be that it is the last CRD of a list of large CRDs - will have to try shuffling the order in the list.

I perhaps could import the CRDs separately using aliases as described [here](https://github.com/cdk8s-team/cdk8s/issues/883), to work around the fact that the last file of the same API group will overwrite the others, as described [here](https://github.com/cdk8s-team/cdk8s/issues/2156), but this is not ideal.

I'm guessing perhaps the import gets into a infinite recursive loop, as (attempting to) increasing the Node stack size does not improve the issue (editing the cdk8s script):

```shell
#!/usr/bin/env node --stack-size=4096
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('../lib/cli');
```

Possibly related to [this issue](https://github.com/cdk8s-team/cdk8s/issues/951).

**Comment by iliapolo** [comment] 2023-02-11 11:24
@jhwbarlow I'm not able to reproduce the issue with the CRD in the [gist](https://gist.github.com/jhwbarlow/8023d014dc59c63836293580e2dc2575) you provided.

I ran with with: `cdk8s import --language python` and it was successful: 

```console
Importing resources, this may take a few moments...
monitoring.coreos.com
  monitoring.coreos.com/alertmanager
  monitoring.coreos.com/alertmanagerconfig
  monitoring.coreos.com/podmonitor
  monitoring.coreos.com/probe
  monitoring.coreos.com/prometheus
  monitoring.coreos.com/prometheusrule
  monitoring.coreos.com/servicemonitor
  monitoring.coreos.com/thanosruler
>>> elapsed time 11s                   
```

Can you double check this is the one I should be using?

**Comment by ClouderDex** [comment] 2023-05-04 00:23
@jhwbarlow and @iliapolo  - I am getting the same issue importing the CRD below. Have either of you made any progress on this?

https://github.com/splunk/splunk-operator/releases/download/2.2.1/splunk-operator-cluster.yaml

```
% cdk8s import --language python
Importing resources, this may take a few moments...
enterprise.splunk.com
  enterprise.splunk.com/clustermanager
  enterprise.splunk.com/clustermaster
  enterprise.splunk.com/indexercluster
  enterprise.splunk.com/licensemanager
  enterprise.splunk.com/licensemaster
  enterprise.splunk.com/monitoringconsole
  enterprise.splunk.com/searchheadcluster
  enterprise.splunk.com/standalone
NOTE: Temp directory retained due to an error: /var/folders/bz/h8lgc9r11fl93k3pk7rnq0500000gr/T/temp-smLEHT
Error: jsii compilation failed with non-zero exit code: 255
  | Error: RangeError: Maximum call stack size exceeded
  |     at getPipelinePhase (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95407:34)
  |     at pipelineEmit (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95398:33)
  |     at emitExpression (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95384:20)
  |     at emitPropertyAccessExpression (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:96389:38)
  |     at pipelineEmitWithHint (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95780:32)
  |     at pipelineEmitWithSourceMap (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:99003:21)
  |     at pipelineEmitWithComments (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:98747:17)
  |     at maybePipelineEmitExpression (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:96599:21)
  |     at emitBinaryExpression (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:96554:25)
  |     at pipelineEmitWithHint (/usr/local/lib/node_modules/cdk8s-cli/node_modules/typescript/lib/typescript.js:95810:32)
  +----------------------------------------------------------------------------------
  | Command: /usr/local/lib/node_modules/cdk8s-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/bz/h8lgc9r11fl93k3pk7rnq0500000gr/T/temp-smLEHT
  +----------------------------------------------------------------------------------
    at newError (/usr/local/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:62:20)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:79:29)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

```
 % node --version && cdk8s --version
v18.11.0
2.2.27
```

**Comment by iliapolo** [comment] 2023-05-04 11:16
@ClouderDex I was finally able to reproduce and get to the bottom of this using your CRD. Thanks!

Turns out its actually a bug with typescript 3.9 in specific, fairly involved, scenarios. It was fixed in later versions of typescript, which are utilized by the new jsii version. 

So this should be resolved by https://github.com/cdklabs/jsii-srcmak/pull/1118

**Comment by ClouderDex** [comment] 2023-05-04 20:39
I also confirmed the version bump resolved this issue, Thank you!

**Comment by iliapolo** [comment] 2023-05-23 13:02
I see the CLI has been upgraded with the latest version of `jsii-srcmak` that resolves this issue. Closing.

**Closed as completed by iliapolo** 2023-05-23 13:02 UTC
Labels: bug, effort/small, priority/p1
