### ISSUE TITLE
unable to resolve dependency tree version 2.2.12

### ISSUE THREAD

**Issue by eno-conan** [cdk8s-team/cdk8s-cli#900] opened 2023-04-09 12:16 UTC
### Description of the bug:

When following https://cdk8s.io/docs/latest/getting-started there is a error when running cdk8s init typescript-app

### Reproduction Steps:

```
$ npm -g list | grep npm@
├── npm@9.5.0
├── pnpm@7.19.0

$ node -v
18.13.0

$ cdk8s --version
2.2.12

$ cdk8s init typescript-app
Initializing a project from the typescript-app template
```

### Error Log:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cdk8s@1.0.0
npm ERR! Found: constructs@10.1.299
npm ERR! node_modules/constructs
npm ERR!   constructs@"10.1.299" from the root project
npm ERR!   peer constructs@"^10" from cdk8s@2.7.55
npm ERR!   node_modules/cdk8s
npm ERR!     cdk8s@"2.7.55" from the root project
npm ERR!     peer cdk8s@"^2.7.55" from cdk8s-plus-25@2.6.19
npm ERR!     node_modules/cdk8s-plus-25
npm ERR!       cdk8s-plus-25@"2.6.19" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer constructs@"^10.1.306" from cdk8s-plus-25@2.6.19
npm ERR! node_modules/cdk8s-plus-25
npm ERR!   cdk8s-plus-25@"2.6.19" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\enoconan\AppData\Local\npm-cache\_logs\2023-04-09T12_08_51_408Z-eresolve-report.txt     
npm ERR!     C:\Users\enoconan\AppData\Local\npm-cache\_logs\2023-04-09T12_08_51_408Z-debug-0.log
```

### Environment:

  - **Framework Version**: 2.2.12
  - **OS**:windows 11 

### Other:

---

This is :bug: Bug Report

**Comment by sumupitchayan** [comment] 2023-04-12 15:02
This looks related to #827. Another user posted a [comment on how to fix this issue](https://github.com/cdk8s-team/cdk8s-cli/issues/827#issuecomment-1439481052) - can you try this suggestion and see if it solves your problem?

> It looks like as a result of this the package.json is generated without any packages installed. No node_modules directory is present.
> 
> ```json
> {
>   "name": "cdk_test",
>   "version": "1.0.0",
>   "main": "main.js",
>   "types": "main.ts",
>   "license": "Apache-2.0",
>   "private": true,
>   "scripts": {
>     "import": "cdk8s import",
>     "synth": "cdk8s synth",
>     "compile": "tsc --build",
>     "watch": "tsc --build -w",
>     "test": "jest",
>     "build": "npm run compile && npm run test && npm run synth",
>     "upgrade": "npm i cdk8s@latest cdk8s-cli@latest",
>     "upgrade:next": "npm i cdk8s@next cdk8s-cli@next"
>   }
> }
> ```
> 
> Running `npm i cdk8s@latest --save` works without issue.

**Comment by iliapolo** [comment] 2023-05-07 16:22
Closing as duplicate of https://github.com/cdk8s-team/cdk8s-cli/issues/827

**Closed as completed by iliapolo** 2023-05-07 16:22 UTC
Labels: bug, duplicate
